# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 646)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(550, 190, 271, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(90, 10, 91, 16))
        self.label_6.setObjectName("label_6")
        self.output = QtWidgets.QTextBrowser(self.frame)
        self.output.setEnabled(False)
        self.output.setGeometry(QtCore.QRect(20, 30, 231, 31))
        self.output.setObjectName("output")
        self.OutputData = QtWidgets.QLineEdit(self.frame)
        self.OutputData.setEnabled(False)
        self.OutputData.setGeometry(QtCore.QRect(130, 120, 121, 20))
        self.OutputData.setObjectName("OutputData")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(130, 90, 111, 16))
        self.label_4.setObjectName("label_4")
        self.InputData = QtWidgets.QLineEdit(self.frame)
        self.InputData.setEnabled(False)
        self.InputData.setGeometry(QtCore.QRect(10, 120, 111, 20))
        self.InputData.setObjectName("InputData")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 51, 20))
        self.label_5.setObjectName("label_5")
        self.StepLine = QtWidgets.QLineEdit(self.frame)
        self.StepLine.setEnabled(False)
        self.StepLine.setGeometry(QtCore.QRect(80, 170, 51, 20))
        self.StepLine.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.StepLine.setCursorPosition(1)
        self.StepLine.setObjectName("StepLine")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(290, 10, 221, 411))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_8.setObjectName("label_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 201, 371))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 430, 841, 121))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 811, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InputLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.InputLabel.setObjectName("InputLabel")
        self.horizontalLayout.addWidget(self.InputLabel)
        self.Data = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.Data.setObjectName("Data")
        self.horizontalLayout.addWidget(self.Data)
        self.AX = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.AX.setObjectName("AX")
        self.horizontalLayout.addWidget(self.AX)
        self.BX = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.BX.setObjectName("BX")
        self.horizontalLayout.addWidget(self.BX)
        self.CX = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.CX.setObjectName("CX")
        self.horizontalLayout.addWidget(self.CX)
        self.DX = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.DX.setObjectName("DX")
        self.horizontalLayout.addWidget(self.DX)
        self.AXH = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.AXH.setObjectName("AXH")
        self.horizontalLayout.addWidget(self.AXH)
        self.AXL = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.AXL.setObjectName("AXL")
        self.horizontalLayout.addWidget(self.AXL)
        self.BXH = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.BXH.setObjectName("BXH")
        self.horizontalLayout.addWidget(self.BXH)
        self.BXL = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.BXL.setObjectName("BXL")
        self.horizontalLayout.addWidget(self.BXL)
        self.CXH = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.CXH.setObjectName("CXH")
        self.horizontalLayout.addWidget(self.CXH)
        self.CXL = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.CXL.setObjectName("CXL")
        self.horizontalLayout.addWidget(self.CXL)
        self.DXH = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.DXH.setObjectName("DXH")
        self.horizontalLayout.addWidget(self.DXH)
        self.DXL = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.DXL.setObjectName("DXL")
        self.horizontalLayout.addWidget(self.DXL)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 810, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OutpuLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.OutpuLabel.setObjectName("OutpuLabel")
        self.horizontalLayout_2.addWidget(self.OutpuLabel)
        self.AXo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.AXo.setObjectName("AXo")
        self.horizontalLayout_2.addWidget(self.AXo)
        self.BXo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.BXo.setObjectName("BXo")
        self.horizontalLayout_2.addWidget(self.BXo)
        self.CXo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.CXo.setObjectName("CXo")
        self.horizontalLayout_2.addWidget(self.CXo)
        self.DXo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.DXo.setObjectName("DXo")
        self.horizontalLayout_2.addWidget(self.DXo)
        self.AXHo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.AXHo.setObjectName("AXHo")
        self.horizontalLayout_2.addWidget(self.AXHo)
        self.AXLo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.AXLo.setObjectName("AXLo")
        self.horizontalLayout_2.addWidget(self.AXLo)
        self.BXHo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.BXHo.setObjectName("BXHo")
        self.horizontalLayout_2.addWidget(self.BXHo)
        self.BXLo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.BXLo.setObjectName("BXLo")
        self.horizontalLayout_2.addWidget(self.BXLo)
        self.CXHo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.CXHo.setObjectName("CXHo")
        self.horizontalLayout_2.addWidget(self.CXHo)
        self.CXLo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.CXLo.setObjectName("CXLo")
        self.horizontalLayout_2.addWidget(self.CXLo)
        self.DXHo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.DXHo.setObjectName("DXHo")
        self.horizontalLayout_2.addWidget(self.DXHo)
        self.DXLo = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.DXLo.setObjectName("DXLo")
        self.horizontalLayout_2.addWidget(self.DXLo)
        self.DataToRegister = QtWidgets.QLineEdit(self.frame_3)
        self.DataToRegister.setGeometry(QtCore.QRect(50, 10, 51, 16))
        self.DataToRegister.setText("")
        self.DataToRegister.setObjectName("DataToRegister")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 31, 16))
        self.label_2.setObjectName("label_2")
        self.AddStep = QtWidgets.QPushButton(self.frame_3)
        self.AddStep.setGeometry(QtCore.QRect(150, 92, 75, 21))
        self.AddStep.setObjectName("AddStep")
        self.Operation = QtWidgets.QComboBox(self.frame_3)
        self.Operation.setGeometry(QtCore.QRect(80, 92, 61, 20))
        self.Operation.setObjectName("Operation")
        self.Operation.addItem("")
        self.Operation.addItem("")
        self.Operation.addItem("")
        self.Operation.addItem("")
        self.Operation.addItem("")
        self.Operation.addItem("")
        self.Operation.addItem("")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 271, 411))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 251, 311))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label_7.setObjectName("label_7")
        self.DeleteLine = QtWidgets.QPushButton(self.frame_4)
        self.DeleteLine.setGeometry(QtCore.QRect(10, 350, 191, 23))
        self.DeleteLine.setObjectName("DeleteLine")
        self.LineNo = QtWidgets.QLineEdit(self.frame_4)
        self.LineNo.setGeometry(QtCore.QRect(200, 351, 61, 21))
        self.LineNo.setText("")
        self.LineNo.setObjectName("LineNo")
        self.DeleteProgram = QtWidgets.QPushButton(self.frame_4)
        self.DeleteProgram.setGeometry(QtCore.QRect(10, 380, 251, 23))
        self.DeleteProgram.setObjectName("DeleteProgram")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 560, 841, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.Execute = QtWidgets.QPushButton(self.frame_5)
        self.Execute.setGeometry(QtCore.QRect(680, 10, 101, 23))
        self.Execute.setObjectName("Execute")
        self.StepByStep = QtWidgets.QPushButton(self.frame_5)
        self.StepByStep.setGeometry(QtCore.QRect(600, 10, 75, 23))
        self.StepByStep.setObjectName("StepByStep")
        self.LoadFile = QtWidgets.QPushButton(self.frame_5)
        self.LoadFile.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.LoadFile.setObjectName("LoadFile")
        self.Save = QtWidgets.QPushButton(self.frame_5)
        self.Save.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.Save.setObjectName("Save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project Broda Pietruszka"))
        self.label_6.setText(_translate("MainWindow", "Output console"))
        self.label_4.setText(_translate("MainWindow", "Output register data"))
        self.label_3.setText(_translate("MainWindow", "Input register data"))
        self.label_5.setText(_translate("MainWindow", "Next step "))
        self.StepLine.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Operation description"))
        self.InputLabel.setText(_translate("MainWindow", "Input register"))
        self.Data.setText(_translate("MainWindow", "Data"))
        self.AX.setText(_translate("MainWindow", "AX"))
        self.BX.setText(_translate("MainWindow", "BX"))
        self.CX.setText(_translate("MainWindow", "CX"))
        self.DX.setText(_translate("MainWindow", "DX"))
        self.AXH.setText(_translate("MainWindow", "AXH"))
        self.AXL.setText(_translate("MainWindow", "AXL"))
        self.BXH.setText(_translate("MainWindow", "BXH"))
        self.BXL.setText(_translate("MainWindow", "BXL"))
        self.CXH.setText(_translate("MainWindow", "CXH"))
        self.CXL.setText(_translate("MainWindow", "CXL"))
        self.DXH.setText(_translate("MainWindow", "DXH"))
        self.DXL.setText(_translate("MainWindow", "DXL"))
        self.OutpuLabel.setText(_translate("MainWindow", "Output register"))
        self.AXo.setText(_translate("MainWindow", "AX"))
        self.BXo.setText(_translate("MainWindow", "BX"))
        self.CXo.setText(_translate("MainWindow", "CX"))
        self.DXo.setText(_translate("MainWindow", "DX"))
        self.AXHo.setText(_translate("MainWindow", "AXH"))
        self.AXLo.setText(_translate("MainWindow", "AXL"))
        self.BXHo.setText(_translate("MainWindow", "BXH"))
        self.BXLo.setText(_translate("MainWindow", "BXL"))
        self.CXHo.setText(_translate("MainWindow", "CXH"))
        self.CXLo.setText(_translate("MainWindow", "CXL"))
        self.DXHo.setText(_translate("MainWindow", "DXH"))
        self.DXLo.setText(_translate("MainWindow", "DXL"))
        self.label_2.setText(_translate("MainWindow", "Data:"))
        self.AddStep.setText(_translate("MainWindow", "Add Step"))
        self.Operation.setItemText(0, _translate("MainWindow", "ADD"))
        self.Operation.setItemText(1, _translate("MainWindow", "SUB"))
        self.Operation.setItemText(2, _translate("MainWindow", "MOV"))
        self.Operation.setItemText(3, _translate("MainWindow", "PUSH"))
        self.Operation.setItemText(4, _translate("MainWindow", "POP"))
        self.Operation.setItemText(5, _translate("MainWindow", "INT21"))
        self.Operation.setItemText(6, _translate("MainWindow", "INT33"))
        self.label.setText(_translate("MainWindow", "Operation"))
        self.label_7.setText(_translate("MainWindow", "Command line"))
        self.DeleteLine.setText(_translate("MainWindow", "Delete Line"))
        self.DeleteProgram.setText(_translate("MainWindow", "Delete Program"))
        self.Execute.setText(_translate("MainWindow", "Execute Program"))
        self.StepByStep.setText(_translate("MainWindow", "Step by Step"))
        self.LoadFile.setText(_translate("MainWindow", "Load File"))
        self.Save.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
